<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_samplepdf_fa fa-ellipsis-v we-pl-1 we-pr-1</name>
   <tag></tag>
   <elementGuidId>45c37317-a2aa-415b-8adb-7755f37f39c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='documents-wrapper']/table/tbody/tr/td[2]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-v we-pl-1 we-pr-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documents-wrapper&quot;)/table[@class=&quot;we-table we-table-wrap-md documents-list questionnaire-templates-list&quot;]/tbody[1]/tr[1]/td[@class=&quot;we-text-md-center&quot;]/div[@class=&quot;we-dropdown&quot;]/a[@class=&quot;we-dropdown-toggle-no-icon we-dropdown-toggle&quot;]/i[@class=&quot;fa fa-ellipsis-v we-pl-1 we-pr-1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='documents-wrapper']/table/tbody/tr/td[2]/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
