<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WC PP Coffee_faux-selection-arrow</name>
   <tag></tag>
   <elementGuidId>ea758961-e32e-48c8-abcf-da4e78faaf59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='events_edit_ysmtaqbkip_new_event']/section[5]/fieldset/div/div/label/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.faux-selection-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>faux-selection-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;events_edit_ysmtaqbkip_new_event&quot;)/section[@class=&quot;session-only&quot;]/fieldset[@class=&quot;event-type-session event-type-specific form-group hide-if-empty-wrapper&quot;]/div[@class=&quot;we-row we-row-has-h-inner-spacing&quot;]/div[@class=&quot;we-col hide-if-empty we-col-sm-6&quot;]/label[@class=&quot;input-wrapper&quot;]/div[@class=&quot;faux-select-wrapper faux-combo-box faux-contents-opened&quot;]/span[@class=&quot;faux-selection-arrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='events_edit_ysmtaqbkip_new_event']/section[5]/fieldset/div/div/label/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/div/span</value>
   </webElementXpaths>
</WebElementEntity>
