version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@8.0.5
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/Prod Testing'
