<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AutoClient dropdown</name>
   <tag></tag>
   <elementGuidId>4242bfe5-f463-4ada-ae7e-4fc0e24e0beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='consumers-list-edit']/table/tbody/tr/td[4]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-v</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consumers-list-edit&quot;)/table[@class=&quot;we-table we-table-wrap-lg edit-consumers-list we-mt-1&quot;]/tbody[1]/tr[1]/td[@class=&quot;options-cell we-text-lg-center&quot;]/div[@class=&quot;we-dropdown-large we-text-left we-pl-1 we-pr-1 we-dropdown&quot;]/a[@class=&quot;we-dropdown-toggle-no-icon we-dropdown-toggle&quot;]/span[@class=&quot;fa fa-ellipsis-v&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consumers-list-edit']/table/tbody/tr/td[4]/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
