<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ P2B_faux-selection-indicator</name>
   <tag></tag>
   <elementGuidId>1dce0c92-7e9d-419b-8af4-06b94ae4f23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div[2]/div/div/div/ul/li/form/fieldset[3]/label/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> faux-selection-indicator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;we-page-header&quot;]/div[@class=&quot;we-row&quot;]/div[@class=&quot;we-col we-col-md-6 we-text-center we-text-md-right we-mt-1 we-mt-md-0&quot;]/div[@class=&quot;we-page-controls we-page-controls-big-buttons&quot;]/div[@class=&quot;we-dropdown-auto-width we-dropdown-left we-dropdown-md-right we-dropdown-fixed-arrows we-dropdown&quot;]/div[@class=&quot;we-dropdown-menu-wrapper&quot;]/ul[@class=&quot;calendar-filtering-form-wrapper we-text-left we-dropdown-menu&quot;]/li[@class=&quot;we-dropdown-menu-item we-pt-1 we-pl-1 we-pr-1&quot;]/form[@class=&quot;spartan-ui&quot;]/fieldset[@class=&quot;provider-fieldset&quot;]/label[@class=&quot;input-wrapper&quot;]/div[@class=&quot;faux-select-wrapper faux-contents-unopened&quot;]/span[@class=&quot;faux-selection-indicator&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[2]/div/div/div/ul/li/form/fieldset[3]/label/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/label/div/span</value>
   </webElementXpaths>
</WebElementEntity>
