version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.2
jobs:
  setup_mailhog:
    docker:
      - image: mailhog/mailhog:latest # primary container
    steps:
      - run: docker run mailhog/mailhog:latest
workflows:
  build:
    jobs:
      - katalon-studio/run:
          requires:
            -setup_mailhog
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/Prod Testing'
