version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.2
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/Prod Testing'
      docker:
        - image: mailhog/mailhog:latest # primary container
