version: 2.1

orbs:
  node: circleci/node@4.1.0

workflow:
  build:
    jobs:
        katalon-studio/run: 
        version: latest
        command_arguments: >-
          -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/Prod Testing'
  test:
    jobs:
      executor:
        name: node/default
        tag: '10.15.3'
        working_directory: /root/project
        steps:
          - checkout
          - run: |
            set -ex
            npm: install
            npm: test
        - persist_to_workspace:
        root: /root/project
        paths:
          - report/*
      upload-report:
        docker:
          - image: katalonstudio/report-uploader:0.0.8
        environment:
          PROJECT_ID: 145957
          TYPE: katalon
          REPORT_PATH: CircleCI Automation Test Results
        steps:
          - attach_workspace:
            at: /katalon
          - run: uploader.sh
