version: 2.1

orbs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
        name: Prod Pexip Testing
        command: katalon-execute.sh -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/Prod Testing'
      - store-test_results:
        path: ./report
      - store-artifacts:
        path: ./report
