<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left Pane Attendees</name>
   <tag></tag>
   <elementGuidId>49a9a44f-a378-498c-b00e-dee3594569c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M91.9,44.1c-3,2.5-6.9,4-11.1,4c-2.2,0-4.2-0.4-6.1-1.1c1.3,2.5,2,5.4,2,8.5v23.3H100V56.4C100,50.9,96.7,46.2,91.9,44.1z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;session_frame&quot;]/div[1]/div/button[3]</value>
   </webElementProperties>
</WebElementEntity>
