<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sessionSelectLocation</name>
   <tag></tag>
   <elementGuidId>096913fb-1217-4dc7-9345-b53021729f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.locations</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_WeCounsel/schedule check/iframe__iframe-frontend-scheduling-wizard</value>
   </webElementProperties>
</WebElementEntity>
