<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UH Video</name>
   <tag></tag>
   <elementGuidId>d5bf309b-26dc-4339-86f6-1aca69b39289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M93.1,23.5L72.9,35v-3.7c0-6.6-5.4-12-12-12H12c-6.6,0-12,5.4-12,12v37.4c0,6.6,5.4,12,12,12h49c6.6,0,12-5.4,12-12v-3.7 l20.1,11.6c3.8,2.2,6.9,0.4,6.9-4v-45C100,23.1,96.9,21.3,93.1,23.5z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;session_videos_wrap&quot;]/div[3]/div/button[3]</value>
   </webElementProperties>
</WebElementEntity>
