<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ WeCounsel 2011 - 2020_iframe-fronte_98eb21</name>
   <tag></tag>
   <elementGuidId>51702078-4437-48e3-9d6b-b1d5e0cc226a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.iframe-frontend-scheduling-wizard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-frontend-scheduling-wizard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/scheduler?version=1.0.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;internal user-type-provider application-controller-session_events session_events application-action-upcoming_sessions upcoming_sessions considered-directory-used private-practice use-main-sidebar&quot;]/iframe[@class=&quot;iframe-frontend-scheduling-wizard&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
   </webElementXpaths>
</WebElementEntity>
