<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<WebElementEntity>
   <description/>
   <name>input_Guest email_eventguest_users_attributes1590605518942email</name>
   <tag/>
   <elementGuidId>e8cf0abd-dd7d-4b03-b810-a7fea665fe18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/fieldset/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#events_edit_sptcntyiqa_event_guest_users_attributes_1590605178413_email</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email' and @name = 'event[guest_users_attributes][1590605518942][email]' and @id = 'events_edit_ismxmfpnde_event_guest_users_attributes_1590605518942_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>event[guest_users_attributes][1590605518942][email]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>events_edit_ismxmfpnde_event_guest_users_attributes_1590605518942_email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id("events_edit_ismxmfpnde_event_guest_users_attributes_1590605518942_email")</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screenshot</name>
      <type>Main</type>
      <value>C:/Users/hawki/Katalon Studio/test-pp/Screenshots/Targets/input_Guest email_eventguest_users_attributes1590605518942email.png</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='events_edit_ismxmfpnde_event_guest_users_attributes_1590605518942_email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='events_edit_ismxmfpnde_new_event']/section/fieldset[2]/div/fieldset/label/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/label/input</value>
   </webElementXpaths>
</WebElementEntity>
