<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send Note</name>
   <tag></tag>
   <elementGuidId>dbab048d-c134-4d00-b910-9d8e7b5ec008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-notes-list-container']/div/div/div/div/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-paper-plane-o fa-fw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-notes-list-container&quot;)/div[@class=&quot;we-collapsible-wrapper we-collapsible-v-arrows we-collapsible-no-save-state user-note-item we-collapsible-active we-collapsible-opened   user-note-id-2542&quot;]/div[@class=&quot;user-note-content-wrapper document-associated focused&quot;]/div[@class=&quot;user-note-content&quot;]/div[@class=&quot;document-header&quot;]/span[@class=&quot;document-links&quot;]/a[@class=&quot;document-send-link edit-form-link&quot;]/i[@class=&quot;fa fa-paper-plane-o fa-fw&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-notes-list-container']/div/div/div/div/span/a[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
