<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframe-frontend-scheduling-wizard</name>
   <tag></tag>
   <elementGuidId>3680ab21-0a80-4df9-aeba-9bd19cb3cff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.iframe-frontend-scheduling-wizard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-frontend-scheduling-wizard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/scheduler?version=1.0.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;internal user-type-organization_admin user-type-facilitator user-type-admin application-controller-upcoming_sessions upcoming_sessions application-action-index index considered-directory-used private-practice no-main-sidebar we&quot;]/iframe[@class=&quot;iframe-frontend-scheduling-wizard&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
   </webElementXpaths>
</WebElementEntity>
